repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: Formatting (black)
        entry: black
        language: python
        types_or: [python, pyi, jupyter]
        additional_dependencies: [".[jupyter]"]
      - id: isort
        name: Sorting imports (isort)
        entry: isort
        types: [python]
        language: system
      - id: flake8
        name: Linting (flake8)
        entry: flake8
        types: [python]
        language: system
exclude: ^(.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/|venv/|.venv/)
